apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-e2e-app.fullname" . }}
  labels:
    {{- include "devops-e2e-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devops-e2e-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
