apiVersion: v2
name: devops-e2e-app
description: Helm chart for the devops-e2e-pipeline task API
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/Puja-Dube02/devops-e2e-pipeline
sources:
  - https://github.com/Puja-Dube02/devops-e2e-pipeline
keywords:
  - devops
  - nodejs
  - example
maintainers:
  - name: Puja Dube
